const villesAutourDeNanterre = [
    "Antony",
    "Argenteuil",
    "Arcueil",
    "Asnières-sur-Seine",
    "Bagnet",
    "Bagneux",
    "Bezons",
    "Bois-Colombes",
    "Boulogne-Billancourt",
    "Bourg-la-Reine",
    "Carrières-sur-Seine",
    "Cachan",
    "Chatou",
    "Châtillon",
    "Chaville",
    "Chevilly-Larue",
    "Clamart",
    "Colombes",
    "Courbevoie",
    "Croissy-sur-Seine",
    "Fontenay-aux-Roses",
    "Fresnes",
    "Garches",
    "Gennevilliers",
    "Houilles",
    "Issy-les-Moulineaux",
    "L'Haÿ-les-Roses",
    "La Garenne-Colombes",
    "Le Chesnay-Rocquencourt",
    "Le Vésinet",
    "Levallois-Perret",
    "Malakoff",
    "Meudon",
    "Montrouge",
    "Montesson",
    "Neuilly-sur-Seine",
    "Paris",
    "Puteaux",
    "Rueil-Malmaison",
    "Rungis",
    "Saint-Cloud",
    "Saint-Germain-en-Laye",
    "Sartrouville",
    "Sceaux",
    "Sèvres",
    "Suresnes",
    "Thiais",
    "Vanves",
    "Vaucresson",
    "Versailles",
    "Ville-d'Avray",
    "Viroflay"
];
export default villesAutourDeNanterre